CREATE TABLE IF NOT EXISTS `LieuDung` (
	`MaDonThuoc` VARCHAR(255) NOT NULL,
	`MaThuoc` VARCHAR(255) NOT NULL,
	`SoLuong` INTEGER,
	`LieuDung` VARCHAR(255),
	PRIMARY KEY(`MaDonThuoc`, `MaThuoc`)
);


CREATE TABLE IF NOT EXISTS `DichVuCB` (
	`MaDichVu` VARCHAR(255) NOT NULL,
	`MaCB` VARCHAR(255) NOT NULL,
	`SoLuong` INTEGER,
	`DonGiaApDung` INTEGER,
	PRIMARY KEY(`MaDichVu`, `MaCB`)
);


CREATE TABLE IF NOT EXISTS `DichVuKB` (
	`MaDichVu` VARCHAR(255) NOT NULL,
	`MaKB` VARCHAR(255) NOT NULL,
	`SoLuong` INTEGER,
	`DonGiaApDung` INTEGER,
	PRIMARY KEY(`MaDichVu`, `MaKB`)
);


CREATE TABLE IF NOT EXISTS `PhanCongKB` (
	`MaKB` VARCHAR(255) NOT NULL,
	`MaYT` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`MaKB`, `MaYT`)
);


CREATE TABLE IF NOT EXISTS `DichVu` (
	`MaDichVu` VARCHAR(255) NOT NULL,
	`TenDichVu` VARCHAR(255),
	`MoTa` VARCHAR(255),
	`DonGia` INTEGER,
	PRIMARY KEY(`MaDichVu`)
);


CREATE TABLE IF NOT EXISTS `PhanCongCB` (
	`MaCB` VARCHAR(255) NOT NULL,
	`MaYT` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`MaCB`, `MaYT`)
);


CREATE TABLE IF NOT EXISTS `BenhNhan` (
	`MaBN` VARCHAR(255) NOT NULL,
	`TenBN` VARCHAR(255),
	`GioiTinh` VARCHAR(255),
	`NgaySinh` DATE,
	`DiaChi` VARCHAR(255),
	`SDT` VARCHAR(255),
	PRIMARY KEY(`MaBN`)
);


CREATE TABLE IF NOT EXISTS `Khoa` (
	`MaKhoa` VARCHAR(255) NOT NULL,
	`TenKhoa` VARCHAR(255),
	`MoTa` TEXT,
	PRIMARY KEY(`MaKhoa`)
);


CREATE TABLE IF NOT EXISTS `BacSy` (
	`MaBS` VARCHAR(255) NOT NULL,
	`MaKhoa` VARCHAR(255) NOT NULL,
	`TenBS` VARCHAR(255),
	`GioiTinh` VARCHAR(255),
	`PhongKham` VARCHAR(255) NOT NULL,
	`NamKinhNghiem` INTEGER,
	`HeSoLuong` DECIMAL(5,2),
	PRIMARY KEY(`MaBS`)
);


CREATE TABLE IF NOT EXISTS `YTa` (
	`MaYT` VARCHAR(255) NOT NULL,
	`TenYT` VARCHAR(255),
	`GioiTinh` VARCHAR(255),
	`BoPhan` VARCHAR(255),
	`NamKinhNghiem` INTEGER,
	`HeSoLuong` DECIMAL(5,2),
	PRIMARY KEY(`MaYT`)
);


CREATE TABLE IF NOT EXISTS `HoSoBenhAn` (
	`MaBA` VARCHAR(255) NOT NULL,
	`MaBN` VARCHAR(255) NOT NULL,
	`MaCD` VARCHAR(255) NOT NULL,
	`TrangThai` VARCHAR(255),
	`ThoiGianMo` DATETIME NOT NULL,
	`ThoiGianKetThuc` DATETIME,
	`MaBS` VARCHAR(255),
	PRIMARY KEY(`MaBA`)
);


CREATE TABLE IF NOT EXISTS `KhamBenh` (
	`MaKB` VARCHAR(255) NOT NULL,
	`MaBN` VARCHAR(255) NOT NULL,
	`MaBS` VARCHAR(255) NOT NULL,
	`ThoiGian` DATETIME NOT NULL,
	PRIMARY KEY(`MaKB`)
);


CREATE TABLE IF NOT EXISTS `ChuaBenh` (
	`MaCB` VARCHAR(255) NOT NULL,
	`MaBenh` VARCHAR(255) NOT NULL,
	`MaBA` VARCHAR(255) NOT NULL,
	`HinhThucChuaBenh` VARCHAR(255),
	`ThoiGian` DATETIME NOT NULL,
	PRIMARY KEY(`MaCB`)
);


CREATE TABLE IF NOT EXISTS `Benh` (
	`MaBenh` VARCHAR(255) NOT NULL,
	`TenBenh` VARCHAR(255),
	`MoTa` VARCHAR(255),
	PRIMARY KEY(`MaBenh`)
);


CREATE TABLE IF NOT EXISTS `DonThuoc` (
	`MaDonThuoc` VARCHAR(255) NOT NULL,
	`MaCB` VARCHAR(255) NOT NULL,
	`NgayLapDon` DATETIME NOT NULL,
	PRIMARY KEY(`MaDonThuoc`)
);


CREATE TABLE IF NOT EXISTS `Thuoc` (
	`MaThuoc` VARCHAR(255) NOT NULL,
	`TenThuoc` VARCHAR(255),
	`MoTa` VARCHAR(255),
	`DonViTinh` VARCHAR(255),
	`DonGia` INTEGER,
	PRIMARY KEY(`MaThuoc`)
);


CREATE TABLE IF NOT EXISTS `ChanDoan` (
	`MaCD` VARCHAR(255) NOT NULL,
	`MaKB` VARCHAR(255),
	`MaBenh` VARCHAR(255),
	`MucDo` VARCHAR(255),
	`SoLanChuaBenhDuDoan` INTEGER,
	PRIMARY KEY(`MaCD`)
);

CREATE TABLE IF NOT EXISTS `ThietBiYTe` (
	`MaThietBi` VARCHAR(255) NOT NULL,
	`TenThietBi` VARCHAR(255),
	`DonGia` VARCHAR(255),
	PRIMARY KEY(`MaThietBi`)
);

CREATE TABLE IF NOT EXISTS `SuDungThietBiCB` (
	`MaThietBi` VARCHAR(255) NOT NULL,
	`MaCB` VARCHAR(255) NOT NULL,
	`SoLuong` INTEGER,
	`DonGiaApDung` INTEGER,
	PRIMARY KEY(`MaThietBi`, `MaCB`)
);


CREATE TABLE IF NOT EXISTS `SuDungThietBiKB` (
	`MaThietBi` VARCHAR(255) NOT NULL,
	`MaKB` VARCHAR(255) NOT NULL,
	`SoLuong` INTEGER,
	`DonGiaApDung` INTEGER,
	PRIMARY KEY(`MaThietBi`, `MaKB`)
);


ALTER TABLE `BacSy`
ADD FOREIGN KEY(`MaKhoa`) REFERENCES `Khoa`(`MaKhoa`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ChanDoan`
ADD FOREIGN KEY(`MaBenh`) REFERENCES `Benh`(`MaBenh`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PhanCongCB`
ADD FOREIGN KEY(`MaYT`) REFERENCES `YTa`(`MaYT`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `HoSoBenhAn`
ADD FOREIGN KEY(`MaBN`) REFERENCES `BenhNhan`(`MaBN`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `KhamBenh`
ADD FOREIGN KEY(`MaBN`) REFERENCES `BenhNhan`(`MaBN`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `HoSoBenhAn`
ADD FOREIGN KEY(`MaCD`) REFERENCES `ChanDoan`(`MaCD`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ChuaBenh`
ADD FOREIGN KEY(`MaBA`) REFERENCES `HoSoBenhAn`(`MaBA`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `HoSoBenhAn`
ADD FOREIGN KEY(`MaBS`) REFERENCES `BacSy`(`MaBS`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `KhamBenh`
ADD FOREIGN KEY(`MaBS`) REFERENCES `BacSy`(`MaBS`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PhanCongCB`
ADD FOREIGN KEY(`MaCB`) REFERENCES `ChuaBenh`(`MaCB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PhanCongKB`
ADD FOREIGN KEY(`MaKB`) REFERENCES `KhamBenh`(`MaKB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PhanCongKB`
ADD FOREIGN KEY(`MaYT`) REFERENCES `YTa`(`MaYT`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DichVuKB`
ADD FOREIGN KEY(`MaDichVu`) REFERENCES `DichVu`(`MaDichVu`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DichVuCB`
ADD FOREIGN KEY(`MaDichVu`) REFERENCES `DichVu`(`MaDichVu`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DichVuKB`
ADD FOREIGN KEY(`MaKB`) REFERENCES `KhamBenh`(`MaKB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DichVuCB`
ADD FOREIGN KEY(`MaCB`) REFERENCES `ChuaBenh`(`MaCB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `LieuDung`
ADD FOREIGN KEY(`MaDonThuoc`) REFERENCES `DonThuoc`(`MaDonThuoc`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `LieuDung`
ADD FOREIGN KEY(`MaThuoc`) REFERENCES `Thuoc`(`MaThuoc`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DonThuoc`
ADD FOREIGN KEY(`MaCB`) REFERENCES `ChuaBenh`(`MaCB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ChuaBenh`
ADD FOREIGN KEY(`MaBenh`) REFERENCES `Benh`(`MaBenh`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ChanDoan`
ADD FOREIGN KEY(`MaKB`) REFERENCES `KhamBenh`(`MaKB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `SuDungThietBiKB`
ADD FOREIGN KEY(`MaThietBi`) REFERENCES `ThietBiYTe`(`MaThietBi`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `SuDungThietBiKB`
ADD FOREIGN KEY(`MaKB`) REFERENCES `KhamBenh`(`MaKB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `SuDungThietBiCB`
ADD FOREIGN KEY(`MaThietBi`) REFERENCES `ThietBiYTe`(`MaThietBi`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `SuDungThietBiCB`
ADD FOREIGN KEY(`MaCB`) REFERENCES `ChuaBenh`(`MaCB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;