SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS DonThuoc;
DROP TABLE IF EXISTS LieuDung;
DROP TABLE IF EXISTS Thuoc;

DROP TABLE IF EXISTS DichVuCB;
DROP TABLE IF EXISTS DichVuKB;
DROP TABLE IF EXISTS DichVu;

DROP TABLE IF EXISTS PhanCongKB;
DROP TABLE IF EXISTS PhanCongCB;
DROP TABLE IF EXISTS YTa;

DROP TABLE IF EXISTS SuDungThietBiCB;
DROP TABLE IF EXISTS SuDungThietBiKB;
DROP TABLE IF EXISTS ThietBiYTe;

DROP TABLE IF EXISTS ChuaBenh;
DROP TABLE IF EXISTS HoSoBenhAn;
DROP TABLE IF EXISTS ChanDoan;
DROP TABLE IF EXISTS KhamBenh;

DROP TABLE IF EXISTS BenhNhan;
DROP TABLE IF EXISTS BacSy;
DROP TABLE IF EXISTS Benh;
DROP TABLE IF EXISTS Khoa;

SET FOREIGN_KEY_CHECKS = 1;
