const PREFIX = 'DEPARTMENT/'

const departmentAction = {
    GET_DEPARTMENTS : PREFIX + 'GET_DEPARTMENTS',
    GET_DEPARTMENTS_SUCCESS : PREFIX + 'GET_DEPARTMENTS_SUCCESS',
    GET_DEPARTMENTS_FAIL : PREFIX + 'GET_DOCGET_DEPARTMENTS_FAILTORS',

    GET_DEPARTMENTS_BY_PAGING : PREFIX + 'GET_DEPARTMENTS_BY_PAGING',
    GET_DEPARTMENTS_BY_PAGING_SUCCESS : PREFIX + 'GET_DEPARTMENTS_BY_PAGING_SUCCESS',
    GET_DEPARTMENTS_BY_PAGING_FAIL : PREFIX + 'GET_DEPARTMENTS_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default departmentAction;