const PREFIX = 'DISEASE_STATISTIC/'

const diseaseStatisticAction = {
    GET_DISEASES : PREFIX + 'GET_DISEASES',
    GET_DISEASES_SUCCESS : PREFIX + 'GET_DISEASES_SUCCESS',
    GET_DISEASES_FAIL : PREFIX + 'GET_DOCGET_DISEASES_FAILTORS',

    GET_DISEASES_BY_PAGING : PREFIX + 'GET_DISEASES_BY_PAGING',
    GET_DISEASES_BY_PAGING_SUCCESS : PREFIX + 'GET_DISEASES_BY_PAGING_SUCCESS',
    GET_DISEASES_BY_PAGING_FAIL : PREFIX + 'GET_DISEASES_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default diseaseStatisticAction;