const PREFIX = 'DOCTOR/'

const doctorAction = {
    GET_DOCTORS_BY_PAGING : PREFIX + 'GET_DOCTORS_BY_PAGING',
    GET_DOCTORS_BY_PAGING_SUCCESS : PREFIX + 'GET_DOCTORS_BY_PAGING_SUCCESS',
    GET_DOCTORS_BY_PAGING_FAIL : PREFIX + 'GET_DOCTORS_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default doctorAction;