const PREFIX = 'DOCTOR/'

const doctorAction = {
    GET_DOCTORS : PREFIX + 'GET_DOCTORS',
    GET_DOCTORS_SUCCESS : PREFIX + 'GET_DOCTORS_SUCCESS',
    GET_DOCTORS_FAIL : PREFIX + 'GET_DOCGET_DOCTORS_FAILTORS',

    GET_DOCTORS_BY_PAGING : PREFIX + 'GET_DOCTORS_BY_PAGING',
    GET_DOCTORS_BY_PAGING_SUCCESS : PREFIX + 'GET_DOCTORS_BY_PAGING_SUCCESS',
    GET_DOCTORS_BY_PAGING_FAIL : PREFIX + 'GET_DOCTORS_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',

    SELECT_DOCTOR: PREFIX + 'SELECT_DOCTOR',

    SHOW_CREATE_DOCTOR_MODAL: PREFIX + 'SHOW_CREATE_DOCTOR_MODAL',
    HIDE_CREATE_DOCTOR_MODAL: PREFIX + 'HIDE_CREATE_DOCTOR_MODAL',

    GET_DEPARTMENTS : PREFIX + 'GET_DEPARTMENTS',
    GET_DEPARTMENTS_SUCCESS : PREFIX + 'GET_DEPARTMENTS_SUCCESS',
    GET_DEPARTMENTS_FAIL : PREFIX + 'GET_DOCGET_DEPARTMENTS_FAILTORS',

    CREATE_DOCTOR:  PREFIX + 'CREATE_DOCTOR',
    CREATE_DOCTOR_SUCCESS:  PREFIX + 'CREATE_DOCTOR_SUCCESS',
    CREATE_DOCTOR_FAIL:  PREFIX + 'CREATE_DOCTOR_FAIL',

    SHOW_UPDATE_DOCTOR_MODAL: PREFIX + 'SHOW_UPDATE_DOCTOR_MODAL',
    HIDE_UPDATE_DOCTOR_MODAL: PREFIX + 'HIDE_UPDATE_DOCTOR_MODAL',

    UPDATE_DOCTOR:  PREFIX + 'UPDATE_DOCTOR',
    UPDATE_DOCTOR_SUCCESS:  PREFIX + 'UPDATE_DOCTOR_SUCCESS',
    UPDATE_DOCTOR_FAIL:  PREFIX + 'UPDATE_DOCTOR_FAIL',

    SHOW_DELETE_DOCTOR_MODAL: PREFIX + 'SHOW_DELETE_DOCTOR_MODAL',
    HIDE_DELETE_DOCTOR_MODAL: PREFIX + 'HIDE_DELETE_DOCTOR_MODAL',

    DELETE_DOCTOR:  PREFIX + 'DELETE_DOCTOR',
    DELETE_DOCTOR_SUCCESS:  PREFIX + 'DELETE_DOCTOR_SUCCESS',
    DELETE_DOCTOR_FAIL:  PREFIX + 'DELETE_DOCTOR_FAIL',

}

export default doctorAction;