const PREFIX = 'EQUIPMENT/'

const equipmentAction = {
    GET_EQUIPMENTS : PREFIX + 'GET_EQUIPMENTS',
    GET_EQUIPMENTS_SUCCESS : PREFIX + 'GET_EQUIPMENTS_SUCCESS',
    GET_EQUIPMENTS_FAIL : PREFIX + 'GET_DOCGET_EQUIPMENTS_FAILTORS',

    GET_EQUIPMENTS_BY_PAGING : PREFIX + 'GET_EQUIPMENTS_BY_PAGING',
    GET_EQUIPMENTS_BY_PAGING_SUCCESS : PREFIX + 'GET_EQUIPMENTS_BY_PAGING_SUCCESS',
    GET_EQUIPMENTS_BY_PAGING_FAIL : PREFIX + 'GET_EQUIPMENTS_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default equipmentAction;