const PREFIX = 'EQUIQMENT/'

const equiqmentAction = {
    GET_EQUIQMENTS : PREFIX + 'GET_EQUIQMENTS',
    GET_EQUIQMENTS_SUCCESS : PREFIX + 'GET_EQUIQMENTS_SUCCESS',
    GET_EQUIQMENTS_FAIL : PREFIX + 'GET_DOCGET_EQUIQMENTS_FAILTORS',

    GET_EQUIQMENTS_BY_PAGING : PREFIX + 'GET_EQUIQMENTS_BY_PAGING',
    GET_EQUIQMENTS_BY_PAGING_SUCCESS : PREFIX + 'GET_EQUIQMENTS_BY_PAGING_SUCCESS',
    GET_EQUIQMENTS_BY_PAGING_FAIL : PREFIX + 'GET_EQUIQMENTS_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default equiqmentAction;