const PREFIX = 'EXAMINATION/'

const examinationAction = {
    GET_EXAMINATIONS : PREFIX + 'GET_EXAMINATIONS',
    GET_EXAMINATIONS_SUCCESS : PREFIX + 'GET_EXAMINATIONS_SUCCESS',
    GET_EXAMINATIONS_FAIL : PREFIX + 'GET_DOCGET_EXAMINATIONS_FAILTORS',

    GET_EXAMINATIONS_BY_PAGING : PREFIX + 'GET_EXAMINATIONS_BY_PAGING',
    GET_EXAMINATIONS_BY_PAGING_SUCCESS : PREFIX + 'GET_EXAMINATIONS_BY_PAGING_SUCCESS',
    GET_EXAMINATIONS_BY_PAGING_FAIL : PREFIX + 'GET_EXAMINATIONS_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default examinationAction;