const PREFIX = 'EXAMINATION/'

const examinationAction = {
    GET_EXAMINATIONS : PREFIX + 'GET_EXAMINATIONS',
    GET_EXAMINATIONS_SUCCESS : PREFIX + 'GET_EXAMINATIONS_SUCCESS',
    GET_EXAMINATIONS_FAIL : PREFIX + 'GET_DOCGET_EXAMINATIONS_FAILTORS',

    GET_EXAMINATIONS_BY_PAGING : PREFIX + 'GET_EXAMINATIONS_BY_PAGING',
    GET_EXAMINATIONS_BY_PAGING_SUCCESS : PREFIX + 'GET_EXAMINATIONS_BY_PAGING_SUCCESS',
    GET_EXAMINATIONS_BY_PAGING_FAIL : PREFIX + 'GET_EXAMINATIONS_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',

    SELECT_EXAMINATION: PREFIX + 'SELECT_EXAMINATION',

    SHOW_CREATE_EXAMINATION_MODAL: PREFIX + 'SHOW_CREATE_EXAMINATION_MODAL',
    HIDE_CREATE_EXAMINATION_MODAL: PREFIX + 'HIDE_CREATE_EXAMINATION_MODAL',

    GET_DEPARTMENTS : PREFIX + 'GET_DEPARTMENTS',
    GET_DEPARTMENTS_SUCCESS : PREFIX + 'GET_DEPARTMENTS_SUCCESS',
    GET_DEPARTMENTS_FAIL : PREFIX + 'GET_DOCGET_DEPARTMENTS_FAILTORS',

    CREATE_EXAMINATION:  PREFIX + 'CREATE_EXAMINATION',
    CREATE_EXAMINATION_SUCCESS:  PREFIX + 'CREATE_EXAMINATION_SUCCESS',
    CREATE_EXAMINATION_FAIL:  PREFIX + 'CREATE_EXAMINATION_FAIL',

    SHOW_UPDATE_EXAMINATION_MODAL: PREFIX + 'SHOW_UPDATE_EXAMINATION_MODAL',
    HIDE_UPDATE_EXAMINATION_MODAL: PREFIX + 'HIDE_UPDATE_EXAMINATION_MODAL',

    UPDATE_EXAMINATION:  PREFIX + 'UPDATE_EXAMINATION',
    UPDATE_EXAMINATION_SUCCESS:  PREFIX + 'UPDATE_EXAMINATION_SUCCESS',
    UPDATE_EXAMINATION_FAIL:  PREFIX + 'UPDATE_EXAMINATION_FAIL',

    SHOW_DELETE_EXAMINATION_MODAL: PREFIX + 'SHOW_DELETE_EXAMINATION_MODAL',
    HIDE_DELETE_EXAMINATION_MODAL: PREFIX + 'HIDE_DELETE_EXAMINATION_MODAL',

    DELETE_EXAMINATION:  PREFIX + 'DELETE_EXAMINATION',
    DELETE_EXAMINATION_SUCCESS:  PREFIX + 'DELETE_EXAMINATION_SUCCESS',
    DELETE_EXAMINATION_FAIL:  PREFIX + 'DELETE_EXAMINATION_FAIL',
}

export default examinationAction;