const PREFIX = 'MEDICAL_RECORD/'

const medicalRecordAction = {
    GET_MEDICAL_RECORDS : PREFIX + 'GET_MEDICAL_RECORDS',
    GET_MEDICAL_RECORDS_SUCCESS : PREFIX + 'GET_MEDICAL_RECORDS_SUCCESS',
    GET_MEDICAL_RECORDS_FAIL : PREFIX + 'GET_DOCGET_MEDICAL_RECORDS_FAILTORS',

    GET_MEDICAL_RECORDS_BY_PAGING : PREFIX + 'GET_MEDICAL_RECORDS_BY_PAGING',
    GET_MEDICAL_RECORDS_BY_PAGING_SUCCESS : PREFIX + 'GET_MEDICAL_RECORDS_BY_PAGING_SUCCESS',
    GET_MEDICAL_RECORDS_BY_PAGING_FAIL : PREFIX + 'GET_MEDICAL_RECORDS_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',

    SELECT_MEDICAL_RECORD: PREFIX + 'SELECT_MEDICAL_RECORD',

    SHOW_CREATE_MEDICAL_RECORD_MODAL: PREFIX + 'SHOW_CREATE_MEDICAL_RECORD_MODAL',
    HIDE_CREATE_MEDICAL_RECORD_MODAL: PREFIX + 'HIDE_CREATE_MEDICAL_RECORD_MODAL',

    GET_DEPARTMENTS : PREFIX + 'GET_DEPARTMENTS',
    GET_DEPARTMENTS_SUCCESS : PREFIX + 'GET_DEPARTMENTS_SUCCESS',
    GET_DEPARTMENTS_FAIL : PREFIX + 'GET_DOCGET_DEPARTMENTS_FAILTORS',

    CREATE_MEDICAL_RECORD:  PREFIX + 'CREATE_MEDICAL_RECORD',
    CREATE_MEDICAL_RECORD_SUCCESS:  PREFIX + 'CREATE_MEDICAL_RECORD_SUCCESS',
    CREATE_MEDICAL_RECORD_FAIL:  PREFIX + 'CREATE_MEDICAL_RECORD_FAIL',

    SHOW_UPDATE_MEDICAL_RECORD_MODAL: PREFIX + 'SHOW_UPDATE_MEDICAL_RECORD_MODAL',
    HIDE_UPDATE_MEDICAL_RECORD_MODAL: PREFIX + 'HIDE_UPDATE_MEDICAL_RECORD_MODAL',

    UPDATE_MEDICAL_RECORD:  PREFIX + 'UPDATE_MEDICAL_RECORD',
    UPDATE_MEDICAL_RECORD_SUCCESS:  PREFIX + 'UPDATE_MEDICAL_RECORD_SUCCESS',
    UPDATE_MEDICAL_RECORD_FAIL:  PREFIX + 'UPDATE_MEDICAL_RECORD_FAIL',

    SHOW_DELETE_MEDICAL_RECORD_MODAL: PREFIX + 'SHOW_DELETE_MEDICAL_RECORD_MODAL',
    HIDE_DELETE_MEDICAL_RECORD_MODAL: PREFIX + 'HIDE_DELETE_MEDICAL_RECORD_MODAL',

    DELETE_MEDICAL_RECORD:  PREFIX + 'DELETE_MEDICAL_RECORD',
    DELETE_MEDICAL_RECORD_SUCCESS:  PREFIX + 'DELETE_MEDICAL_RECORD_SUCCESS',
    DELETE_MEDICAL_RECORD_FAIL:  PREFIX + 'DELETE_MEDICAL_RECORD_FAIL',
}

export default medicalRecordAction;