const PREFIX = 'MEDICINE/'

const medicineAction = {
    GET_MEDICINES : PREFIX + 'GET_MEDICINES',
    GET_MEDICINES_SUCCESS : PREFIX + 'GET_MEDICINES_SUCCESS',
    GET_MEDICINES_FAIL : PREFIX + 'GET_DOCGET_MEDICINES_FAILTORS',

    GET_MEDICINES_BY_PAGING : PREFIX + 'GET_MEDICINES_BY_PAGING',
    GET_MEDICINES_BY_PAGING_SUCCESS : PREFIX + 'GET_MEDICINES_BY_PAGING_SUCCESS',
    GET_MEDICINES_BY_PAGING_FAIL : PREFIX + 'GET_MEDICINES_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default medicineAction;