const PREFIX = 'NURSE/'

const nurseAction = {
    GET_NURSES : PREFIX + 'GET_NURSES',
    GET_NURSES_SUCCESS : PREFIX + 'GET_NURSES_SUCCESS',
    GET_NURSES_FAIL : PREFIX + 'GET_DOCGET_NURSES_FAILTORS',

    GET_NURSES_BY_PAGING : PREFIX + 'GET_NURSES_BY_PAGING',
    GET_NURSES_BY_PAGING_SUCCESS : PREFIX + 'GET_NURSES_BY_PAGING_SUCCESS',
    GET_NURSES_BY_PAGING_FAIL : PREFIX + 'GET_NURSES_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default nurseAction;