const PREFIX = 'NURSE_SALARY/'

const nurseSalaryAction = {
    GET_SALARIES : PREFIX + 'GET_SALARIES',
    GET_SALARIES_SUCCESS : PREFIX + 'GET_SALARIES_SUCCESS',
    GET_SALARIES_FAIL : PREFIX + 'GET_DOCGET_SALARIES_FAILTORS',

    GET_SALARIES_BY_PAGING : PREFIX + 'GET_SALARIES_BY_PAGING',
    GET_SALARIES_BY_PAGING_SUCCESS : PREFIX + 'GET_SALARIES_BY_PAGING_SUCCESS',
    GET_SALARIES_BY_PAGING_FAIL : PREFIX + 'GET_SALARIES_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default nurseSalaryAction;