const PREFIX = 'PATIENT/'

const patientAction = {
    GET_PATIENTS : PREFIX + 'GET_PATIENTS',
    GET_PATIENTS_SUCCESS : PREFIX + 'GET_PATIENTS_SUCCESS',
    GET_PATIENTS_FAIL : PREFIX + 'GET_DOCGET_PATIENTS_FAILTORS',

    GET_PATIENTS_BY_PAGING : PREFIX + 'GET_PATIENTS_BY_PAGING',
    GET_PATIENTS_BY_PAGING_SUCCESS : PREFIX + 'GET_PATIENTS_BY_PAGING_SUCCESS',
    GET_PATIENTS_BY_PAGING_FAIL : PREFIX + 'GET_PATIENTS_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default patientAction;