const PREFIX = 'REVENUE/'

const revenueAction = {
    GET_REVENUES : PREFIX + 'GET_REVENUES',
    GET_REVENUES_SUCCESS : PREFIX + 'GET_REVENUES_SUCCESS',
    GET_REVENUES_FAIL : PREFIX + 'GET_DOCGET_REVENUES_FAILTORS',

    GET_REVENUES_BY_PAGING : PREFIX + 'GET_REVENUES_BY_PAGING',
    GET_REVENUES_BY_PAGING_SUCCESS : PREFIX + 'GET_REVENUES_BY_PAGING_SUCCESS',
    GET_REVENUES_BY_PAGING_FAIL : PREFIX + 'GET_REVENUES_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default revenueAction;