const PREFIX = 'SERVICE/'

const serviceAction = {
    GET_SERVICES : PREFIX + 'GET_SERVICES',
    GET_SERVICES_SUCCESS : PREFIX + 'GET_SERVICES_SUCCESS',
    GET_SERVICES_FAIL : PREFIX + 'GET_DOCGET_SERVICES_FAILTORS',

    GET_SERVICES_BY_PAGING : PREFIX + 'GET_SERVICES_BY_PAGING',
    GET_SERVICES_BY_PAGING_SUCCESS : PREFIX + 'GET_SERVICES_BY_PAGING_SUCCESS',
    GET_SERVICES_BY_PAGING_FAIL : PREFIX + 'GET_SERVICES_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',
}

export default serviceAction;