const PREFIX = 'SIDEBAR/'

const sidebarAction = {
    LOAD_MENU:  PREFIX + 'LOAD_MENU',
    LOAD_MENU_SUCCESS:  PREFIX + 'LOAD_MENU_SUCCESS',
    LOAD_MENU_FAIL:  PREFIX + 'LOAD_MENU_FAIL',

    SIDEBAR_EXPAND: PREFIX + 'SIDEBAR_EXPAND',
    SIDEBAR_SHRINK: PREFIX + 'SIDEBAR_SHRINK',
    
    SELECT_ITEM : PREFIX + 'SELECT_ITEM',
    
    GROUP_COLLAPSE: PREFIX + 'GROUP_COLLAPSE',
    GROUP_UNCOLLAPSE: PREFIX + 'GROUP_UNCOLLAPSE',
}

export default sidebarAction;