const PREFIX = 'TREATMENT/'

const treatmentAction = {
    GET_TREATMENTS : PREFIX + 'GET_TREATMENTS',
    GET_TREATMENTS_SUCCESS : PREFIX + 'GET_TREATMENTS_SUCCESS',
    GET_TREATMENTS_FAIL : PREFIX + 'GET_DOCGET_TREATMENTS_FAILTORS',

    GET_TREATMENTS_BY_PAGING : PREFIX + 'GET_TREATMENTS_BY_PAGING',
    GET_TREATMENTS_BY_PAGING_SUCCESS : PREFIX + 'GET_TREATMENTS_BY_PAGING_SUCCESS',
    GET_TREATMENTS_BY_PAGING_FAIL : PREFIX + 'GET_TREATMENTS_BY_PAGING_FAIL',
    
    PAGE_CHANGE : PREFIX + 'PAGE_CHANGE',

    SELECT_TREATMENT: PREFIX + 'SELECT_TREATMENT',

    SHOW_CREATE_TREATMENT_MODAL: PREFIX + 'SHOW_CREATE_TREATMENT_MODAL',
    HIDE_CREATE_TREATMENT_MODAL: PREFIX + 'HIDE_CREATE_TREATMENT_MODAL',

    GET_DEPARTMENTS : PREFIX + 'GET_DEPARTMENTS',
    GET_DEPARTMENTS_SUCCESS : PREFIX + 'GET_DEPARTMENTS_SUCCESS',
    GET_DEPARTMENTS_FAIL : PREFIX + 'GET_DOCGET_DEPARTMENTS_FAILTORS',

    CREATE_TREATMENT:  PREFIX + 'CREATE_TREATMENT',
    CREATE_TREATMENT_SUCCESS:  PREFIX + 'CREATE_TREATMENT_SUCCESS',
    CREATE_TREATMENT_FAIL:  PREFIX + 'CREATE_TREATMENT_FAIL',

    SHOW_UPDATE_TREATMENT_MODAL: PREFIX + 'SHOW_UPDATE_TREATMENT_MODAL',
    HIDE_UPDATE_TREATMENT_MODAL: PREFIX + 'HIDE_UPDATE_TREATMENT_MODAL',

    UPDATE_TREATMENT:  PREFIX + 'UPDATE_TREATMENT',
    UPDATE_TREATMENT_SUCCESS:  PREFIX + 'UPDATE_TREATMENT_SUCCESS',
    UPDATE_TREATMENT_FAIL:  PREFIX + 'UPDATE_TREATMENT_FAIL',

    SHOW_DELETE_TREATMENT_MODAL: PREFIX + 'SHOW_DELETE_TREATMENT_MODAL',
    HIDE_DELETE_TREATMENT_MODAL: PREFIX + 'HIDE_DELETE_TREATMENT_MODAL',

    DELETE_TREATMENT:  PREFIX + 'DELETE_TREATMENT',
    DELETE_TREATMENT_SUCCESS:  PREFIX + 'DELETE_TREATMENT_SUCCESS',
    DELETE_TREATMENT_FAIL:  PREFIX + 'DELETE_TREATMENT_FAIL',
}

export default treatmentAction;